version: '2'
services:
  mongo:
    image: mongo:3.4
  node_modules:
    build:
     context: .
     dockerfile: Dockerfile_nodemodules
  web:
    build: .
    ports:
     - "3000:3000"
     #Comment out for production
    #environment:
    # - PRO_MONGODB_URI=mongodb://mongo:27017/truman
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/starter
     - /starter/node_modules
